### PR TITLE
Improvements to caching and APNS token error handling

### PR DESCRIPTION
**Pull request by danieldaquino**
This PR contains a collection of improvements to notepush, specifically around caching and error handling.

### CODE REVIEW

**Comment by danieldaquino** [comment]
_Note: This is already deployed to the server for prototype testing purposes_

**Comment by jb55** [comment]
nice! the response time is basically instant now

**Comment by jb55** [comment]
oh but it doesn't seem to be sending notifications after the first one...

**Comment by danieldaquino** [comment]
@jb55 I added a commit on this PR that should resolve the app restart/setting reset issue (https://github.com/damus-io/damus/issues/2417)

I also just deployed a new build to staging and production(test) environments with it to help us with testing!

I will keep fixing the other issues

**Review by jb55 — APPROVED** [review]
lgtm!

**Pull request merged**
